// Script pour ajouter les colonnes et tables necessaires pour la facturation mensuelle
const db = require('../config/database');

async function addMonthlyInvoiceSupport() {
    try {
        await db.initialize();
        console.log('Connexion etablie');

        // 1. Verifier si les colonnes invoice_month et invoice_year existent
        console.log('\n--- Verification colonnes invoice_month/invoice_year ---');
        const colCheck = await db.execute(`
            SELECT column_name 
            FROM user_tab_columns 
            WHERE table_name = 'ORDER_INVOICES' 
            AND column_name IN ('INVOICE_MONTH', 'INVOICE_YEAR')
        `);

        const existingCols = colCheck.rows.map(r => r.COLUMN_NAME);
        console.log('Colonnes existantes:', existingCols);

        if (!existingCols.includes('INVOICE_MONTH')) {
            console.log('Ajout colonne INVOICE_MONTH...');
            try {
                await db.execute(`ALTER TABLE order_invoices ADD invoice_month NUMBER(2)`);
                console.log('INVOICE_MONTH ajoutee');
            } catch (e) {
                if (e.message.includes('already exists')) {
                    console.log('Colonne deja existante');
                } else throw e;
            }
        }

        if (!existingCols.includes('INVOICE_YEAR')) {
            console.log('Ajout colonne INVOICE_YEAR...');
            try {
                await db.execute(`ALTER TABLE order_invoices ADD invoice_year NUMBER(4)`);
                console.log('INVOICE_YEAR ajoutee');
            } catch (e) {
                if (e.message.includes('already exists')) {
                    console.log('Colonne deja existante');
                } else throw e;
            }
        }

        // 2. Verifier si la table invoice_delivery_notes existe
        console.log('\n--- Verification table invoice_delivery_notes ---');
        const tableCheck = await db.execute(`
            SELECT table_name 
            FROM user_tables 
            WHERE table_name = 'INVOICE_DELIVERY_NOTES'
        `);

        if (tableCheck.rows.length === 0) {
            console.log('Creation table INVOICE_DELIVERY_NOTES...');
            await db.execute(`
                CREATE TABLE invoice_delivery_notes (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    invoice_id NUMBER NOT NULL,
                    delivery_note_id NUMBER NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_idn_invoice FOREIGN KEY (invoice_id) REFERENCES order_invoices(id),
                    CONSTRAINT fk_idn_delivery FOREIGN KEY (delivery_note_id) REFERENCES delivery_notes(id),
                    CONSTRAINT uk_invoice_delivery UNIQUE (invoice_id, delivery_note_id)
                )
            `);
            console.log('Table INVOICE_DELIVERY_NOTES creee');
        } else {
            console.log('Table INVOICE_DELIVERY_NOTES existe deja');
        }

        // 3. Mettre a jour les factures existantes avec month/year si manquant
        console.log('\n--- Mise a jour factures existantes ---');
        const updateResult = await db.execute(`
            UPDATE order_invoices 
            SET invoice_month = EXTRACT(MONTH FROM created_at),
                invoice_year = EXTRACT(YEAR FROM created_at)
            WHERE invoice_month IS NULL OR invoice_year IS NULL
        `);
        console.log('Factures mises a jour:', updateResult.rowsAffected || 0);

        console.log('\n=== Migration terminee avec succes ===');

    } catch (err) {
        console.error('Erreur:', err);
    } finally {
        await db.close();
        process.exit(0);
    }
}

addMonthlyInvoiceSupport();
