-- ============================================
-- CREATE AGENTS TABLE (linked to AGENCES)
-- ============================================

CREATE TABLE AGENTS (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    NOM VARCHAR2(100) NOT NULL,
    PRENOM VARCHAR2(100),
    TELEPHONE VARCHAR2(20),
    AGENCE_ID NUMBER REFERENCES AGENCES(ID),
    ROLE VARCHAR2(20) DEFAULT 'AGENT' CHECK (ROLE IN ('AGENT', 'ADMIN')),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'SUSPENDED', 'INACTIVE')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN TIMESTAMP
);

-- Index for faster lookups
CREATE INDEX IDX_AGENTS_AGENCE ON AGENTS(AGENCE_ID);
CREATE INDEX IDX_AGENTS_EMAIL ON AGENTS(EMAIL);

-- ============================================
-- FILL AGENCES WITH 3 ROWS IN CASABLANCA
-- ============================================

INSERT INTO AGENCES (CODE, NOM, ADRESSE, VILLE, CODE_POSTAL, TELEPHONE, EMAIL, STATUS)
VALUES ('AG-CASA-01', 'AgriMart Casablanca Centre', '123 Boulevard Mohammed V', 'Casablanca', '20000', '+212 522 123 456', 'centre@agrimart.ma', 'ACTIVE');

INSERT INTO AGENCES (CODE, NOM, ADRESSE, VILLE, CODE_POSTAL, TELEPHONE, EMAIL, STATUS)
VALUES ('AG-CASA-02', 'AgriMart Casablanca Ain Sebaa', '45 Avenue des FAR, Ain Sebaa', 'Casablanca', '20250', '+212 522 234 567', 'ainsebaa@agrimart.ma', 'ACTIVE');

INSERT INTO AGENCES (CODE, NOM, ADRESSE, VILLE, CODE_POSTAL, TELEPHONE, EMAIL, STATUS)
VALUES ('AG-CASA-03', 'AgriMart Casablanca Maarif', '78 Rue Zerktouni, Maarif', 'Casablanca', '20100', '+212 522 345 678', 'maarif@agrimart.ma', 'ACTIVE');

COMMIT;

-- ============================================
-- UPDATE CLIENTS TABLE - Add APPROVED_BY_AGENT column
-- (to track which agent approved the client)
-- ============================================

ALTER TABLE CLIENTS ADD APPROVED_BY_AGENT NUMBER REFERENCES AGENTS(ID);
CREATE INDEX IDX_CLIENTS_APPROVED_BY ON CLIENTS(APPROVED_BY_AGENT);

-- ============================================
-- CREATE SAMPLE AGENTS (run after AGENCES are created)
-- Password: agent123 (bcrypt hashed)
-- ============================================

-- Get agence IDs first, then insert agents
-- Assuming IDs are 1, 2, 3 for the three agences

INSERT INTO AGENTS (EMAIL, PASSWORD, NOM, PRENOM, TELEPHONE, AGENCE_ID, ROLE, STATUS)
VALUES ('agent.centre@agrimart.ma', '$2a$10$8K1p/a0dL1LXMIZoUqM0/.Fe1RQYe3X9X6HHt6G.QD2KhK9pOqHDy', 'Bennani', 'Ahmed', '+212 600 111 111', 1, 'AGENT', 'ACTIVE');

INSERT INTO AGENTS (EMAIL, PASSWORD, NOM, PRENOM, TELEPHONE, AGENCE_ID, ROLE, STATUS)
VALUES ('agent.ainsebaa@agrimart.ma', '$2a$10$8K1p/a0dL1LXMIZoUqM0/.Fe1RQYe3X9X6HHt6G.QD2KhK9pOqHDy', 'El Amrani', 'Fatima', '+212 600 222 222', 2, 'AGENT', 'ACTIVE');

INSERT INTO AGENTS (EMAIL, PASSWORD, NOM, PRENOM, TELEPHONE, AGENCE_ID, ROLE, STATUS)
VALUES ('agent.maarif@agrimart.ma', '$2a$10$8K1p/a0dL1LXMIZoUqM0/.Fe1RQYe3X9X6HHt6G.QD2KhK9pOqHDy', 'Alaoui', 'Mohammed', '+212 600 333 333', 3, 'AGENT', 'ACTIVE');

-- Admin agent (no specific agence, can see all)
INSERT INTO AGENTS (EMAIL, PASSWORD, NOM, PRENOM, TELEPHONE, AGENCE_ID, ROLE, STATUS)
VALUES ('admin@agrimart.ma', '$2a$10$8K1p/a0dL1LXMIZoUqM0/.Fe1RQYe3X9X6HHt6G.QD2KhK9pOqHDy', 'Admin', 'Super', '+212 600 000 000', NULL, 'ADMIN', 'ACTIVE');

COMMIT;



