const oracledb = require('oracledb');
const db = require('../config/db');

exports.createOrder = async (req, res) => {
    const { items, notes } = req.body; // items: [{ product_id, quantity }]
    const clientId = req.user.id; // From auth middleware

    if (!items || items.length === 0) {
        return res.status(400).json({ message: 'Le panier est vide' });
    }

    let connection;
    try {
        connection = await db.getPool().getConnection();

        // Calculate totals and verify stock
        let totalHt = 0;
        const orderItems = [];

        for (const item of items) {
            const prodSql = `SELECT product_id, product_name, prix_unitaire, stock_disponible FROM products WHERE product_id = :id AND is_active = 'Y'`;
            const prodResult = await connection.execute(prodSql, [item.product_id], { outFormat: oracledb.OUT_FORMAT_OBJECT });

            if (prodResult.rows.length === 0) {
                return res.status(400).json({ message: `Produit ID ${item.product_id} non trouvé` });
            }

            const product = prodResult.rows[0];
            if (product.STOCK_DISPONIBLE < item.quantity) {
                return res.status(400).json({ message: `Stock insuffisant pour ${product.PRODUCT_NAME}` });
            }

            const lineTotal = product.PRIX_UNITAIRE * item.quantity;
            totalHt += lineTotal;

            orderItems.push({
                product_id: product.PRODUCT_ID,
                product_name: product.PRODUCT_NAME, // Snapshot
                quantity: item.quantity,
                prix_unitaire: product.PRIX_UNITAIRE,
                total_line: lineTotal
            });
        }

        const tvaRate = 0.20; // 20% TVA default
        const totalTva = totalHt * tvaRate;
        const totalTtc = totalHt + totalTva;

        // Start Transaction
        // Insert Order
        // Note: ID and Order Number generated by triggers
        const orderSql = `
            INSERT INTO orders (client_id, total_ht, total_tva, total_ttc, notes, status)
            VALUES (:client_id, :total_ht, :total_tva, :total_ttc, :notes, 'PENDING')
            RETURNING id INTO :id
        `;

        const orderResult = await connection.execute(orderSql, {
            client_id: clientId,
            total_ht: totalHt,
            total_tva: totalTva,
            total_ttc: totalTtc,
            notes: notes || '',
            id: { type: oracledb.NUMBER, dir: oracledb.BIND_OUT }
        }, { autoCommit: false });

        const orderId = orderResult.outBinds.id[0];

        // Insert Order Items
        const itemSql = `
            INSERT INTO order_items (order_id, product_id, product_name, quantity, prix_unitaire, total_line)
            VALUES (:order_id, :product_id, :product_name, :quantity, :prix_unitaire, :total_line)
        `;

        for (const item of orderItems) {
            await connection.execute(itemSql, {
                order_id: orderId,
                product_id: item.product_id,
                product_name: item.product_name,
                quantity: item.quantity,
                prix_unitaire: item.prix_unitaire,
                total_line: item.total_line
            }, { autoCommit: false });

            // Optional: Decrement stock
            await connection.execute(
                `UPDATE products SET stock_disponible = stock_disponible - :qty WHERE product_id = :id`,
                { qty: item.quantity, id: item.product_id },
                { autoCommit: false }
            );
        }

        await connection.commit();

        res.status(201).json({ message: 'Commande créée avec succès', orderId });

    } catch (err) {
        if (connection) {
            try { await connection.rollback(); } catch (e) { console.error(e); }
        }
        console.error(err);
        res.status(500).json({ message: 'Erreur lors de la création de la commande' });
    } finally {
        if (connection) {
            try { await connection.close(); } catch (e) { console.error(e); }
        }
    }
};

exports.getOrders = async (req, res) => {
    const clientId = req.user.id;
    let connection;
    try {
        connection = await db.getPool().getConnection();

        const sql = `SELECT * FROM orders WHERE client_id = :id ORDER BY created_at DESC`;
        const result = await connection.execute(sql, [clientId], { outFormat: oracledb.OUT_FORMAT_OBJECT });

        res.json(result.rows);
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Erreur lors de la récupération des commandes' });
    } finally {
        if (connection) {
            try { await connection.close(); } catch (e) { console.error(e); }
        }
    }
};

exports.getOrderById = async (req, res) => {
    const orderId = req.params.id;
    const clientId = req.user.id;
    let connection;
    try {
        connection = await db.getPool().getConnection();

        // Check ownership
        const orderSql = `SELECT * FROM orders WHERE id = :id AND client_id = :client_id`;
        const orderResult = await connection.execute(orderSql, [orderId, clientId], { outFormat: oracledb.OUT_FORMAT_OBJECT });

        if (orderResult.rows.length === 0) {
            return res.status(404).json({ message: 'Commande non trouvée' });
        }

        const itemsSql = `SELECT * FROM order_items WHERE order_id = :id`;
        const itemsResult = await connection.execute(itemsSql, [orderId], { outFormat: oracledb.OUT_FORMAT_OBJECT });

        res.json({
            ...orderResult.rows[0],
            items: itemsResult.rows
        });
    } catch (err) {
        console.error(err);
        res.status(500).json({ message: 'Erreur lors de la récupération de la commande' });
    } finally {
        if (connection) {
            try { await connection.close(); } catch (e) { console.error(e); }
        }
    }
};
