const db = require('./config/database');

async function init() {
    try {
        await db.initialize();
        const connection = await db.getConnection();

        // Create UTILISATEURS table
        try {
            await connection.execute(`
                CREATE TABLE utilisateurs (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    email VARCHAR2(255) UNIQUE NOT NULL,
                    mot_de_passe VARCHAR2(255) NOT NULL,
                    nom VARCHAR2(100),
                    prenom VARCHAR2(100),
                    role_id NUMBER DEFAULT 3,
                    statut VARCHAR2(20) DEFAULT 'ACTIF',
                    telephone VARCHAR2(20),
                    date_creation DATE DEFAULT SYSDATE
                )
            `);
            console.log('Table UTILISATEURS created');
        } catch (e) {
            if (e.message.includes('ORA-00955')) {
                console.log('Table UTILISATEURS already exists');
            } else {
                console.error('Error creating table:', e);
            }
        }

        // Add default comptable
        try {
            await connection.execute(`
                MERGE INTO utilisateurs u
                USING (SELECT 'compta@agri.com' as email FROM dual) d
                ON (u.email = d.email)
                WHEN NOT MATCHED THEN
                    INSERT (email, mot_de_passe, nom, prenom, role_id, statut)
                    VALUES ('compta@agri.com', 'Agri2024!', 'Comptable', 'Principal', 3, 'ACTIF')
            `);
            console.log('Default comptable added/verified');
        } catch (e) {
            console.error('Error adding user:', e);
        }

        // Add roles table just in case
        try {
            await connection.execute(`
                CREATE TABLE roles (
                    id NUMBER PRIMARY KEY,
                    nom VARCHAR2(50) NOT NULL
                )
            `);
            await connection.execute(`INSERT INTO roles VALUES (1, 'ADMIN')`);
            await connection.execute(`INSERT INTO roles VALUES (2, 'DIRECTEUR')`);
            await connection.execute(`INSERT INTO roles VALUES (3, 'COMPTABLE')`);
            console.log('Table ROLES created');
        } catch (e) {
            if (e.message.includes('ORA-00955')) console.log('Table ROLES already exists');
        }

        await connection.close();
        await db.close();
        console.log('Initialization complete');
    } catch (err) {
        console.error('Init failed:', err);
    }
}

init();
